# Generated by Django 3.2.7 on 2021-09-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preço',
            new_name='preco',
        ),
    ]
