# Generated by Django 3.2.7 on 2021-09-13 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_preço_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
