# Generated by Django 3.2.7 on 2021-09-14 18:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210914_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='produto',
            name='image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='image_4',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='produto',
            name='image_5',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255),
        ),
    ]
